species:
  heterozygosity: 0.001
  ploidy: 2
  genome-size: 3.5e9
  germline-mutation-rate: 1.2e-8

samples:
  brain:
    inheritance:
      mendelian:
        from:
          - mother
          - father
  blood:
    inheritance:
      mendelian:
        from:
          - mother
          - father
  mother:
    sex: female
  father:
    sex: male

events:
  denovo: "(brain:0.5 | brain:1.0 | blood:0.5 | brain:1.0) & father:0.0 & mother:0.0"
  not interesting: "!father:0.0 | !mother:0.0 | (brain: 0.0 & blood:0.0)"